__version__ = "1.0.1"
__app_name__ = "API 5L PSL2 & BOTAŞ Pipe QA/QC & Wall Thickness Design Suite"
__author__ = "BOTAŞ & API 5L Pipeline Engineering"
__license__ = "MIT"
__release_date__ = "2026-08-21"
